default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: WaiterApp_development

test:
  <<: *default
  database: WaiterApp_test

production:
  adapter: postgresql
  encoding: unicode
  database: WaiterApp_production
  username: WaiterApp
  password: <%= ENV['WAITERAPP_DATABASE_PASSWORD'] %>
