export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART"
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART"
export const CLEAR_ITEMS_FROM_CART = "CLEAR_ITEMS_FROM_CART"

export const SHOW_FLASH = "SHOW_FLASH"
export const HIDE_FLASH = "HIDE_FLASH"
